import type { Metadata } from "next";

import {orbitron, oranienbaum} from "./fonts"

import "./index.css";
import Providers from "@/common/contexts/Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${orbitron.variable} ${oranienbaum.variable}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
